### PR TITLE
improve tfiles header

### PR DESCRIPTION
**Pull request by ferchaure**
Hi I was reading this file, and I think this changes improve the text header of the tfiles.

Cheers,
Fer

### CODE REVIEW

**Comment by ferchaure** [comment]
maybe the raw times are in unix time or something like that and not in seconds, but It's not clear

**Comment by adredish** [comment]
The times saved in the .t files are in units of 0.1 ms (1/10 ms), which is
a legacy from an old Neuralynx format.
They should be aligned to whatever times are being given to MClust.
The times within MClust itself are in standard matlab double floating point
in seconds.

adr

**Comment by ferchaure** [comment]
> The times within MClust itself are in standard matlab double floating point

I got that from the code, but some of the file extension save the times after casting to uint without multiplying to 10000 (the raw formats). I was asking for that cases...
Maybe they are there for backward compatibility if the spikes are loaded with times in 1/10 ms instead of seconds?

**Comment by adredish** [comment]
The .rawXYZ formats don't change and just spit it out in whatever format
you sent it into.
The .tXYZ formats shift it to 1/10ms.

adr

**Comment by ferchaure** [comment]
then for .rawXYZ formats the unit should be something like: **(same as input)** ? 
What do you think? otherwise a user could think that the values are in some specific time unit

**Comment by adredish** [comment]
Sure.

adr

**Comment by ferchaure** [comment]
Cool, I added my last edition to the text in the files (you can accept if you like). 

I added the endianness to the text, in this way any user can load a t32 ot t64 file without any other documentation.
Little-endian is the default in many systems and without that information is not possible read the file.

**Pull request merged**
